/**
 * Represents all events avaliable to the bot.
 */
const ClientEvents = [
	// 'channelCreate',
	// 'channelDelete',
	// 'channelPinsUpdate',
	// 'channelUpdate',
	// 'clientUserGuildSettingsUpdate',
	// 'clientUserSettingsUpdate',
	"debug",
	"disconnect",
	// 'emojiCreate',
	// 'emojiDelete',
	// 'emojiUpdate',
	"error",
	"guildBanAdd",
	"guildBanRemove",
	"guildCreate",
	"guildDelete",
	"guildMemberAdd",
	// 'guildMemberAvailable',
	"guildMemberRemove",
	// 'guildMembersChunk',
	// 'guildMemberSpeaking',
	"guildMemberUpdate",
	"guildUnavailable",
	"guildUpdate",
	"message",
	"messageDelete",
	// 'messageDeleteBulk',
	// 'messageReactionAdd',
	// 'messageReactionRemove',
	// 'messageReactionRemoveAll',
	"messageUpdate",
	// 'presenceUpdate',
	"ready",
	"reconnecting",
	"resume",
	"roleCreate",
	"roleDelete",
	"roleUpdate",
	// 'typingStart',
	// 'typingStop',
	// 'userNoteUpdate',
	// 'userUpdate',
	// 'voiceStateUpdate',
	"warn"
];

export default ClientEvents;
